services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - OCTANE_SERVER=frankenphp
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - APP_ENV=production
      - APP_DEBUG=false
      - QUEUE_CONNECTION=database
    depends_on:
      - db
      - app
    command: >
      sh -c "
        echo 'Waiting for main app to be ready...' &&
        sleep 30 &&
        php artisan queue:work --verbose --sleep=3 --tries=3 --max-time=3600 --timeout=60
      "

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
      - app
    command: >
      sh -c "
        echo 'Starting Laravel scheduler...' &&
        while true; do
          php artisan schedule:run --verbose --no-interaction &
          sleep 60
        done
      "

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql

# Volumes needed for Caddy certificates and configuration
volumes:
  db-data:
  caddy_data:
  caddy_config: