FROM dunglas/frankenphp:php8.2-alpine

RUN apk add --no-cache \
    zip \
    libzip-dev \
    freetype \
    libjpeg-turbo \
    libpng \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    nodejs \
    npm

RUN install-php-extensions \
    pcntl \
	pdo_mysql \
	gd \
	intl \
    imap \
    bcmath \
    # redis \
    curl \
	ctype \
	dom \
    exif \
	fileinfo \
	filter \
    hash \
    iconv \
    json \
    mbstring \
    mysqli \
    mysqlnd \
	tokenizer \
	openssl \
    pcre \
	pdo \
	session \
    xml \
    libxml \
    zlib \
	zip

	
COPY . /app

COPY start-dev.sh /usr/local/bin/start-dev.sh
RUN chmod +x /usr/local/bin/start-dev.sh

WORKDIR /app

RUN npm install

EXPOSE 8000 5173

# Default command
CMD ["/usr/local/bin/start-dev.sh"]

# ENTRYPOINT ["php", "artisan", "octane:frankenphp"]